table AMZN
	lineageTag: fb6a3c13-ef25-4a7a-8a49-60fa772f0be9

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ed312e9d-8fa9-4aee-b665-2e69bf23e5d0
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 3db7b551-9fc7-41f6-9ad4-a2e091aa2ee3
			defaultHierarchy: LocalDateTable_d34526d5-2014-4cfe-a125-b6ad1b5f4665.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 115faa33-155f-4461-9baa-34325bbcc699
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 3aadc01e-a8b1-42a1-8f35-1eb29800509b
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 894005cd-1507-44c7-95e7-eca1444446a1
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: cb6214f0-2388-4fdc-aabd-dc714a323959
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: adedb8c7-8349-4ef7-86d2-23ac3b09a234
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 3caea6fc-9abf-42b3-844a-b718147db3da
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Github\Power_BI_Repo\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

